INSERT INTO indicator values (1, 'Entradas telemáticas - Mensual', 'Sarrera telemátikoak - Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (2, 'Salidas SIR - Mensual', 'SIR irteerak - Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (3, 'Facturas telemáticas - Mensual', 'Faktura telematikoak - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (4, 'Expedientes abiertos - Mensual', 'Espediente zabalduta – Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (5, 'Notificaciones postales - Mensual', 'Jakinarazpen postalak – Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (6, 'Notificaciones telemáticas - Mensual', 'Jakinarazpen telematikoak – Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (7, 'Publicaciones en el tablón de anuncios en papel - Mensual', 'Iragarki taula argitalpenak paparean – Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (8, 'Publicaciones en el tablón de anuncios en telemáticas - Mensual', 'Iragarki taula argitalpenak telematikoak – Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (9, 'Volantes de empadronamiento en el cajero ciudadano - Mensual', 'Errolda agiriak herritarren kutxazainean - Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (10, 'Volantes de empadronamiento por interoperabilidad - Mensual', 'Errolda agiriak interoperabilidade bidez - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (11, 'Volantes de empadronamiento en el SAC - Mensual', 'Errolda agiriak HAZean - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (12, 'Pagos en el cajero ciudadano - Mensual', 'Ordainketak herritar kutxazainean- Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (13, 'Pagos a través de mipago - Mensual', 'Ordainetak Mipago pasarelatik - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (14, 'Pagos en el SAC - Mensual', 'Ordainetak HAZean - Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (15, 'Mensajes de Whatsapp recibidos - Mensual', 'Whatappsez jasotako mezuak - Hilero', '[\"ROLE_HAZ\"]');
INSERT INTO indicator values (16, 'Visitas a la web municipal - Mensual', 'Udalwebguneko bisitak - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (17, 'Visitas a la sede electrónica - Mensual', 'Egoitza elektronikoko bisitak - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (18, '% de documentos firmados digitalmente - Trimestral', 'Digitalki sinatutako documentuak % - Hiruhilabetero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (19, '% de expedientes electrónicos - Trimestral', 'Espediente elektronikoen % - Hiruhilabetero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (20, '% de expedientes archivados electrónicamente - Mensual', 'Artxibatutako Espediente elektronikoen % - Hilero', '[\"ROLE_INFORMATIKA\"]');
INSERT INTO indicator values (21, '% de flujos de información realizados - Mensual', 'Egindako Informazio fluxuen % - Hilero', '[\"ROLE_INFORMATIKA\"]');